/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        WordChoser choser = new WordChoser();
        Game game = new Game(choser);
        Scanner userInput = new Scanner(System.in);

        System.out.println("Welcome! Today the word to guess is:");
        while (game.getRemainingAttempts() > 0) {
            System.out.println(game.getWordToGuess());
            System.out.printf("Enter one letter to guess (%d attempts remaining):", game.getRemainingAttempts());
            Character guessedLetter = userInput.nextLine().charAt(0);
            Boolean result = game.guessLetter(guessedLetter);
            if (result) {
                System.out.println("Right!");
            } else {
                System.out.println("Wrong...");
            }
        }
    }
}
